package session

import (
	"context"
	"time"
)

// Service is a session storage service.
// It provides methods for managing sessions and their events.
type Service interface {
	Create(context.Context, *CreateRequest) (*CreateResponse, error)
	Get(context.Context, *GetRequest) (*GetResponse, error)
	List(context.Context, *ListRequest) (*ListResponse, error)
	Delete(context.Context, *DeleteRequest) error
	// AppendEvent appends an event to a session and processes state deltas.
	AppendEvent(context.Context, Session, *Event) error
}

// CreateRequest represents a request to create a session.
type CreateRequest struct {
	AppName string
	UserID  string
	// SessionID is the client-provided ID. Optional: if not set, it will be autogenerated.
	SessionID string
	// State is the initial state of the session.
	State map[string]any
}

// CreateResponse represents a response for a newly created session.
type CreateResponse struct {
	Session Session
}

// GetRequest represents a request to get a session.
type GetRequest struct {
	AppName   string
	UserID    string
	SessionID string

	// NumRecentEvents returns at most N most recent events. Optional.
	NumRecentEvents int
	// After returns events with timestamp >= the given time. Optional.
	After time.Time
}

// GetResponse represents a response from Service.Get.
type GetResponse struct {
	Session Session
}

// ListRequest represents a request to list sessions.
type ListRequest struct {
	AppName string
	UserID  string
}

// ListResponse represents a response from Service.List.
type ListResponse struct {
	Sessions []Session
}

// DeleteRequest represents a request to delete a session.
type DeleteRequest struct {
	AppName   string
	UserID    string
	SessionID string
}
